import { throwErrorA } from './fail-stack-trace-a.js';

it('test 1', () => {
  throwErrorA();
});
