it('custom error', () => {
  throw new Error('a custom error thrown');
});
